// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzP3uapB6o4SFcKf62z7xNko7w0ixbeFY',
    appId: '1:23637583754:web:6131c12e3300e52356ca73',
    messagingSenderId: '23637583754',
    projectId: 'alumni-portal-54d75',
    authDomain: 'alumni-portal-54d75.firebaseapp.com',
    storageBucket: 'alumni-portal-54d75.firebasestorage.app',
    measurementId: 'G-D1HL7FCTQP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf-mYeqVzvg2fNuYEaEUG0FRRbiMnJGYo',
    appId: '1:23637583754:android:c9a0fdd3a628899a56ca73',
    messagingSenderId: '23637583754',
    projectId: 'alumni-portal-54d75',
    storageBucket: 'alumni-portal-54d75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApWYcQoETG7rvk1JN46cwzRtDknySyrjQ',
    appId: '1:23637583754:ios:89bf7aa1a5519bf656ca73',
    messagingSenderId: '23637583754',
    projectId: 'alumni-portal-54d75',
    storageBucket: 'alumni-portal-54d75.firebasestorage.app',
    iosBundleId: 'com.example.alumniPortal',
  );

}